from prompts.claim_dissect import DISSECT_CLAIM
from langchain_openai.chat_models import ChatOpenAI
from langchain.prompts import ChatPromptTemplate
import os
from dotenv import load_dotenv
load_dotenv()
openai_api_key = os.environ.get("OPENAI_API_KEY")
llm = ChatOpenAI(model="gpt-4o-mini", api_key=openai_api_key)


def claim_disintegration(claims:str, prompt: str, llm) -> str:
    """
    Uses a language model to disintegrate claims into their components using the provided prompt.

    Args:
        prompt (str): The system prompt guiding the disintegration.
        claims (str): The claims to disintegrate.

    Returns:
        str: A string of disintegrated claims generated by the LLM.
    """
    final_prompt = ChatPromptTemplate.from_messages([
        ("system", prompt.format(text=claims)),
        ("human", "{text}"),
    ])

    chain = final_prompt | llm

    response = chain.invoke({'text': "Generate the claims"}) 

    response = response.content 

    claim_list = [claim for claim in response.split("\n") if claim]

    return claim_list

claim = '''Around 150 Blinkit gig workers went on a strike in Varanasi, Uttar Pradesh this weekend demanding fair pay, better working conditions and cotton uniforms for the summer. They now claim that the Zomato-owned grocery delivery platform responded by blocking their IDs – citing the strike as the reason – and made them sign an agreement to have their IDs unblocked.
The recent 90-day tariff truce between the United States and China, which saw the US reducing tariffs on Chinese goods from 145% to 30%, has significant implications for India. 
Virat Kohli retires from test match cricket.'''
response = [claim for claim in claim_disintegration(claim, DISSECT_CLAIM, llm) if claim]
