import os
from langchain.prompts import ChatPromptTemplate

def claim_disintegration(claims:str, prompt: str, llm) -> str:
    """
    Uses a language model to disintegrate claims into their components using the provided prompt.

    Args:
        prompt (str): The system prompt guiding the disintegration.
        claims (str): The claims to disintegrate.

    Returns:
        str: A string of disintegrated claims generated by the LLM.
    """
    final_prompt = ChatPromptTemplate.from_messages([
        ("system", prompt),
        ("human", '{claims}'),
    ])

    chain = final_prompt | llm

    response = chain.invoke({"claims":claims})     

    response = response.content 

    claim_list = [claim for claim in response.split("\n") if claim]

    return claim_list