import os
from langchain_core.prompts import ChatPromptTemplate


def generate_keywords(claim:str, prompt: str, llm) -> str:
    """
    Uses a language model to generate keywords from the given article using the provided prompt.

    Args:
        prompt (str): The system prompt guiding the keyword generation.
        article (str): The article content to process.

    Returns:
        str: A string of keywords extracted/generated by the LLM.
    """

    final_prompt = ChatPromptTemplate.from_messages([
        ('system',prompt),
        ('human',"{input}")
    ])

    chain = final_prompt | llm

    response = chain.invoke({
        'input': claim
    })

    return f"'{response.content}'"