import os
from dotenv import load_dotenv

from prompts.keywords import GENERATE_KEYWORDS

from langchain_openai.chat_models import ChatOpenAI
from langchain.schema import SystemMessage, HumanMessage

def generate_keywords(claim:str, prompt: str, llm) -> str:
    """
    Uses a language model to generate keywords from the given article using the provided prompt.

    Args:
        prompt (str): The system prompt guiding the keyword generation.
        article (str): The article content to process.

    Returns:
        str: A string of keywords extracted/generated by the LLM.
    """

    system_message = SystemMessage(content=prompt)
    human_message = HumanMessage(content=claim)

    response = llm.invoke([system_message, human_message])

    return response.content


